### ISSUE TITLE
Use pypy3 to run all days

### ISSUE THREAD

**Issue by OctaviPascual** [EikaNN/AdventOfCode2017#1]
Pypy3 is faster than Python. In order to work properly, the following tasks must be performed:

- find a suitable Docker image
- investigate why pypy3 is not working for day 19 (it produces a seg fault which seems quite random, further investigation is needed)

**Comment by EikaNN** [comment]
Finally I had to change day 19 solution by implementing an iterative function instead of a recursive one.
